### ISSUE TITLE
Stop using lambda functions in React jsx

### ISSUE THREAD

**Issue by hzy** [HUSTFE/Ugli-UI#11]
## 问题
当我们在编写 jsx 时，可能会不由自主的写lambda函数，例如这样：
```jsx
<div
  className={classes('ugli-range-container', { rtl, vertical })}
  onTouchStart={e => this.touchStartHandler(e)} // #1
  onTouchEnd={() => this.touchEndHandler()} // #2
  onTouchMove={throttle(this.touchMoveHandler)} // #3
  onSomeOtherThing={() => this.toggleSomething(false)} // #4
/>
```

但是，我个人认为，这明显会产生一个问题，react 每次render的时候，都会重新生成一个新的匿名函数。
而且，对于 throttle 这样的高阶函数，重新生成消耗更大。

## 提议
我们完全可以bind相关的函数，然后每次render都是简单的取值，而不会重新创建。
对于需要动态参数的函数（不方便bind），采用 lambda 也无可厚非，但是为了统一，动态的值可以在函数内部得到。这样的函数也是可以bind的。
例如：
```js
class Foo extends React.Component{
  ...
  @Bind()
  @Throttle(1000)
  scrollHandler(e) {
    doSomethingWith(e)
  }
  ...
}
```

## 总结
提议完全停止使用 lambda functions in React jsx，提议加入相应的 eslint 规则 react/jsx-no-bind

**Comment by LLGZONE** [comment]
react issue 有过讨论[issue](https://github.com/facebook/react/issues/9851) 使用 classFields 更加方便一些，如果要传参数的话可以使用 arrow function

**Comment by farawaaay** [comment]
应该讨论的不是一个事情

**Comment by farawaaay** [comment]
```js
class MyComponent extends React.Component {
  constructor(props) {
    super(props)
  }

  methodA = () => { ... }
}
```
or

```js
class MyComponent extends React.Component {
  constructor(props) {
    super(props)
    this.methodA = this.methodA.bind(this)
  }

  methodA() { ... }
}
```

跟jsx关系，都不会因为 render 而损失性能

**Comment by farawaaay** [comment]
他们主要是在讨论 `arrow-functions-in-class-properties`

**Comment by LLGZONE** [comment]
[binding in jsx](https://daveceddia.com/avoid-bind-when-passing-props/)

**Comment by farawaaay** [comment]
确实不能用啊，要把 bind 放在render函数外面，避免每次 render 都会去bind，使用装饰器可以避免这个问题，不想用装饰器的话，也可以用`arrow-functions-in-class-properties`

**Comment by LLGZONE** [comment]
看了一下 Ant design 和其他的，一般使用 class field 进行绑定，传参的还是使用 arrow function(一般这种情况很少)

**Comment by LLGZONE** [comment]
那个链接刚贴错了。

**Comment by farawaaay** [comment]
ant design 的做法跟我提议的没什么本质区别

```tsx
export default class Alert extends React.Component<AlertProps, any> {
  ...
  animationEnd = () => {
    this.setState({
      closed: true,
      closing: true,
    });
  }
  ...
  render () {
    return (
      <Animate
        component=""
        showProp="data-show"
        transitionName={`${prefixCls}-slide-up`}
        onEnd={this.animationEnd}
      >
      ...
    )
  }
  ...
}

```

**Comment by farawaaay** [comment]
总之不在render 函数里面bind 就行了
