### ISSUE TITLE
Add `ThemeProvider` for centralized management of theme colors and other props

### ISSUE THREAD

**Issue by farawaaay** [HUSTFE/Ugli-UI#6]
## Problem
Ugli-UI use gradient as a design feature, and it makes no sense to limit user to using only one kind of gradient color. Allowing user to modify the color makes the props become more complex and duplicate.

## Suggestion
To resolve this problem, I think we can use a component like `ThemeProvider`.
In this component, we use context to pass theme color down to all child components.
With the power of context, changing theme in a button click is possible.
We can also allow user to use different theme in a container by use multi-time `ThemeProvider` nestedly.

## Implement
I will create a PR to implemnt this feature.

**Comment by farawaaay** [comment]
Let alone theme colors, it can also 'provide' other theme factor like transition duration and so on.

**Comment by MartinNey** [comment]
I agree on this, it can be useful.

**Comment by farawaaay** [comment]
#7 is the basic implement of the issue.
